### ISSUE TITLE
Benchmarks task not working

### ISSUE THREAD

**Issue by renedeproge** [yosiat/panko_serializer#130]
Hello,

`rake benchmarks` is not working. I [fixed](https://github.com/codingspartan/panko_serializer/tree/fix_benchmarks) some file requirements but looks like something is still wrong:

> panko_serializer/benchmarks/type_casts/bm_panko.rb:7:in `panko_type_convert': undefined method `_type_cast' for Panko:Module (NoMethodError)

I was unable to locate a working version :(

**Comment by yosiat** [comment]
Hey,

This is really bad that all benchmarks doesn't run.. I will think about adding to the CI.

Anyway, I did a branch to fix some of my local issues I had (https://github.com/panko-serializer/panko_serializer/tree/benchmarks-fixes) and I can get `type_casts/bm_panko` to run:
```shell
> export RAILS_VERSION=7.0
> ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
> bundle install
> bundle exec rake
> bundle exec ruby 
```

BTW, In your branch I see you removed this line - `require "panko/panko_serializer"` which is the line responsible for loading the C-extension code.. so it makes sense you won't have the `_type_cast` method (defined here - https://github.com/panko-serializer/panko_serializer/blob/master/ext/panko_serializer/attributes_writer/type_cast/type_cast.c#L362)

**Comment by yosiat** [comment]
I fixed all benchmarks, and they now all pass.
If you see any issue while running them, please re-open this issue.
