### ISSUE TITLE
Serializing data from belongs_to and has_many relationship

### ISSUE THREAD

**Issue by bradbajuz** [yosiat/panko_serializer#24]
I have an Events controller that renders JSON data but have a belongs_to relationship with another model, Offices, and need to render the company attribute in the Event's JSON data.

Office Model:
`has_many :events`

Event Model:
`belongs_to :office`

In my EventSerializer, I can't add:
`belongs_to :office, serializer: OfficeSerializer`

But I need the :company attribute from the Office model and need to turn it into an alias:
```
class EventSerializer < Panko::Serializer
  aliases company: :title
end
```

Is there a way to do this?

**Comment by yosiat** [comment]
@bradbajuz You want that `company` in event serializer will be `office.title` ?

**Comment by bradbajuz** [comment]
When I access the :company attribute from Events, I use office.company.
Current hash that I build and render to JSON: 
```
id: event.id
title: event.office.company
start: event.starttime
end: event.endtime
```

I'm not sure how I would do the same thing when I'm using Panko's serializer. I can easily serialize the event but I also need office.company to show up in my JSON data with an alias of `title`.

So, I guess it would be serializing office under event.

**Comment by yosiat** [comment]
Hi @bradbajuz 

Currently, aliases don't support peeking into relationships.
So your solution is:

```ruby
class EventSerializer < Panko::Serializer
   attributes :id
   aliases endtime: :end, starttime: :start

   def title
       self.object.office.company
   end
end
```

Is that answers your question?

**Comment by bradbajuz** [comment]
Hey @yosiat,

That works great! Appreciate the help. Wanted to make sure I wasn't missing something that might of already been supported in Panko.
