### ISSUE TITLE
Render json for resource

### ISSUE THREAD

**Issue by Kadaaran** [yosiat/panko_serializer#28]
Hello there 👋 

I'm getting this error `undefined method _descriptor' for nil:NilClass` and I have no idea why 🤔 

Here's my line:
`render json: Panko::ArraySerializer.new(@school, serializer: SchoolSerializer).to_json`  

I did not see any example in the documentation for single resource but only for collections am I doing it right ?

Thanks !

**Comment by yosiat** [comment]
Hi @Kadaaran !

Instead of `serializer` you need to write `each_serializer`, so the line should be:
`render json: Panko::ArraySerializer.new(@school, each_serializer: SchoolSerializer).to_json`

I will add code change that detects `each_serializer` is empty and will write some error back.

**Comment by Kadaaran** [comment]
Hi @yosiat !

That's why I did earlier but I ended up with 
`undefined method `to_a' for #<School:0x00007fc15dc6c688> Did you mean? to_s`

**Comment by Kadaaran** [comment]
The weird part is that when I do `render :json @school` it works it just doesn't load all the associations so maybe I miss something here ?

**Comment by yosiat** [comment]
Hola!

If School is one entity you don't need to use `ArraySerializer`, you need to:
```ruby
SchoolSerializer.new.serialize_to_json(@school)
```

Sorry for the confusion!

**Comment by Kadaaran** [comment]
Ooooooh I get it ! Sorry for the dumb question 🙈 thank you so much it works ! 👏 🙌

**Comment by yosiat** [comment]
@Kadaaran This is not a dumb question! it just shows that I need better docs :)
