### ISSUE TITLE
Missing support for rendering hash in Panko::Response

### ISSUE THREAD

**Issue by LaithAzer** [yosiat/panko_serializer#32]
Hi,

Using `Panko::Response.new`, we are not able to render a hash in the response as we get an error thrown `Can not push onto an Object without a key.`.

For example, doing it with normal render json works as follows:

```
my_hash = {
  foo: 'bar',
  bar: 'foo'
}

render json: { my_hash: my_hash }
```

This will give a response looking like: `{"my_hash":{"foo":"bar","bar":"foo"}}`.

However using Panko::Response, the error is thrown:

```
my_hash = {
  foo: 'bar',
  bar: 'foo'
}

render json: Panko::Response.new( my_hash: my_hash )
```

Will give error: `Can not push onto an Object without a key.`.

Please let me know if any additional info is required.

Thanks for this awesome gem!
Laith

**Comment by yosiat** [comment]
Hi @LaithAzer ,

Thanks!

I will look into it today.

**Comment by yosiat** [comment]
Hi @LaithAzer ,

Fixed the issue in the commit above, will release a version today/tomorrow.

Sorry for wait time
