### ISSUE TITLE
undefined symbol: RB_INTEGER_TYPE_P for Fixnum

### ISSUE THREAD

**Issue by Chillwall** [yosiat/panko_serializer#39]
Hi,

I get this error when trying to serialize an object with Fixnum field attribute : 

`symbol lookup error: /usr/local/bundle/gems/panko_serializer-0.5.9/lib/panko/panko_serializer.so: undefined symbol: RB_INTEGER_TYPE_P`

If I use a method attribute to transform it in a String it works fine.

**Comment by yosiat** [comment]
Hi @Chillwall !

Which Ruby version are you using?

**Comment by Chillwall** [comment]
Using ruby 2.3.7

**Comment by yosiat** [comment]
Hola!

Just had the time to work on this.

Fixed in #41 and released a new version - https://rubygems.org/gems/panko_serializer/versions/0.5.10
