### ISSUE TITLE
camelCase method attributes

### ISSUE THREAD

**Issue by Chillwall** [yosiat/panko_serializer#40]
Hello,

I need to use camelCase for my API, what's the best way using Panko?

Right now I uses aliases for most of my attributes and camelCased method names but that feels wrong.

```
class ObjectSerializer < Panko::Serializer
  attributes :title, :methodAttribute
  aliases first_attr: :firstAttr, second_attr: :secondAttr

  def methodAttribute
     compute(object)
  end
end
```

**Comment by dkobia** [comment]
You could also use something like https://github.com/vigetlabs/olive_branch

**Comment by yosiat** [comment]
Hi @Chillwall  !

Sorry for not responding! closing in favour of #52 .
