### ISSUE TITLE
serialize carrierwave mounted field

### ISSUE THREAD

**Issue by xinyou1003** [yosiat/panko_serializer#44]
Hello

I am using carrierwave gem to store the file into s3.

`Album` model has `cover` field and mounted with carrierwave.
It has several versions like `large`, `thumb` and default.

attributes :cover

when I use `Active Model Serializer`, it gives all versions in response
{ cover: {
large: { url: full_url },
thumb: { url: full_url },
url: full_url
}}

but when I use `panko`, it just response the value in `table`. like
{ cover: 'xxx.jpg (not_full_url)` }

Thanks :)

**Comment by mikebaldry** [comment]
you should not expect a serializer to give you an output in a format you expect for an object you have not written a serializer for. Write a serializer for the `CarrierWave::File` (or whatever it may be called) and expose only what you want to expose. That way changes in CarrierWave functionality cannot easily change the output of your API/serializers.

**Comment by yosiat** [comment]
@xinyou1003 what we do in our application is write method attribute to fetch the exact values we need which is what @mikebaldry suggests here as well.

This way you have full control over the data while getting good performance.

**Comment by yosiat** [comment]
@xinyou1003 I am closing the issue, if you disagree with me, let me know I am open for discussion here!
