### ISSUE TITLE
Reusing serializer instance?

### ISSUE THREAD

**Issue by mikebaldry** [yosiat/panko_serializer#47]
I was under the impression that I should be creating a context, then a serializer, then using that serializer many times with many different objects, but when i do that, all results have the same data in them.. Is this a bug?

It works fine if I create a new instance of serializer for each object I want to serialize.

**Comment by yosiat** [comment]
Hi @mikebaldry 

You can't re-use serializer since serializer have state (the object you are serializing).

**Comment by mikebaldry** [comment]
I see. It seems a little wasteful that I need a new serializer for every object I serialize, even if they are instances of the same class. Could the serializer work this way and cache information about the class that is being serialized, to allow it to run more efficiently?

Can I suggest throwing an error if you attempt to use a serializer for a second time? It behaves oddly when serializing another object, but doesn't fail, which I think it should to avoid confusion or bugs.

Thanks

**Comment by mikebaldry** [comment]
I'll PR soon. Thanks
