### ISSUE TITLE
Using with a Hash object?

### ISSUE THREAD

**Issue by mikebaldry** [yosiat/panko_serializer#48]
I'm receiving hashes back from some database calls and serializing the results, this means my object that is getting serialized is a `Hash`. For every item on the `attributes` list, I have to define:

```ruby
def my_attribute
  object["my_attribute"]
end
```

Could panko_serializer support this in a nicer way? Perhaps define a method that does the "getting of an attribute value", instead of using `send(attribute)` - so I could do something like this:

```ruby
class MySerializer < Panko::Serializer
  attributes :cat_name

  private

  def read_attribute(name)
    object[name]
  end
end
```

An alternative would be for me to create a `Struct` for each type of `Hash` result I have, but that would lead to extra allocations and mapping between Hash and Struct that isn't really necessary.

I'd be happy to work on a PR if you think it would be worth including?

**Comment by yosiat** [comment]
@mikebaldry this sounds like a reasonable code change, feel free to PR.

The place you need to look in is - https://github.com/yosiat/panko_serializer/blob/master/ext/panko_serializer/attributes_writer/attributes_writer.c#L31
