### ISSUE TITLE
Setting different key

### ISSUE THREAD

**Issue by VetriVellore** [yosiat/panko_serializer#51]
What would the best way to use a different key for has_one or has_many association?

**Comment by yosiat** [comment]
Hi @VetriVellore ,

By using the different key you mean:
* while reading the object -  the key is `comments`, you want it to access `object.feedback` instead of `comments`
* JSON output - set key "feedback" for "comments" relationship

This is for JSON output:
```
class PostSerializer < Panko::Serializer
	has_many :comments, serializer: CommentSerializer, name: :feedback
end
```

And the JSON output will be:
```
{
	"feedback": [/* array of comments here */]
}
```

**Comment by VetriVellore** [comment]
Thanks Yosiat! Very helpful.

**Comment by VetriVellore** [comment]
I am beginning to use Panko. In my first benchmark, it appears about 5-10% faster than AMS in my dev environment when I measure using Benchmark (without caching for Panko and AMS). I thought it would be significantly faster and am wondering if we are not using Panko correctly. What kinds of things can slow down Panko?

**Comment by VetriVellore** [comment]
@yosiat does name: work with has_one?

**Comment by mikebaldry** [comment]
Why don't you try it?

**Comment by mikebaldry** [comment]
I can see the documentation doesn't mention `name` being supported on `has_one` and `has_many`. This could be improved (also, should probably update with info about serializing a hash)

**Comment by yosiat** [comment]
@VetriVellore `has_one` should work with `name` property as @mikebaldry said.

I'll update the documentation soon, closing the issue for now.
If the has_one + name doesn't work for you please update
