### ISSUE TITLE
Memoized methods cause attributes to leak into other records

### ISSUE THREAD

**Issue by emptyflask** [yosiat/panko_serializer#59]
In the example below, the first user record's `complex_attribute` will override the second.
```ruby
class FooSerializer < Panko::Serializer
  attributes :name, :address, :complex_attribute

  def complex_attribute
    # in reality, something time-consuming
    @complex_attribute ||= [object.name, object.address].join(', ')
  end
end

Panko::ArraySerializer.new(@users, each_serializer: FooSerializer)
```

**Comment by mikebaldry** [comment]
A `Serializer` isn't initialised with a single instance of an object, `render` takes the object to serialize. Therefore using instance variables in a serializer isn't going to be per object. 

I agree this is unexpected from using the `ArraySerializer`, but if you are using normally you do `FooSerializer.new.render(object)` and in that case I wouldn't expect instance variables to work.

**Comment by yosiat** [comment]
@mikebaldry thanks for the explanation.

@emptyflask you need to think about serializers as pure functions with no state and you need to build your application with this in mind.

If you have any more questions/ideas how can I simplify/solve panko to help you better please lmk.

**Comment by emptyflask** [comment]
That makes sense, I was coming at this from Active Model Serializers...
It sounds like I might need a presenter layer between the model and the serializer if I want to create attributes that reference other ones.

**Comment by yosiat** [comment]
@emptyflask I tried thinking about this and I think creating new objects when serializing or adding some caching mechanism support here will complex Panko.

The only solution I can suggest here is using something like `Rails.cache` or passing cache object via the `context`.

**Comment by emptyflask** [comment]
Thanks for looking into it!

**Comment by yosiat** [comment]
@emptyflask I am closing this issue, if you have any idea on how to improve here, please open new issue (and reference this for context if needed).
